# Permalinks
<<<<<<< HEAD
permalink:           pretty

# Setup
title:               Poole
tagline:             The Jekyll Butler
url:                 http://getpoole.com
paginate:            1
baseurl:             ""
=======
permalink:        pretty

# Setup
title:            Yu Feng
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://yuzzfeng.github.io
baseurl:          /
>>>>>>> 4b90f1e3bde494f6bed006f495cbcaee0de9c8d9

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
