# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Yu Feng
tagline:             '@ Leibniz University Hannover'
description:         ''
url:                 https://yuzzfeng.github.io/
baseurl:             https://yuzzfeng.github.io
paginate:            6
github:              https://github.com/yuzzfeng

# About/contact
author:
  name:              Yu Feng
  url:               https://twitter.com/YuFeng10
  email:             yuzz.feng@gmail.com

# Custom vars
version:             1.0.1
