# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Page
tagline:             'Yu Feng'
description:         'A place to save something remarkable'
url:                 https://yuzzfeng.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yu Feng
  url:               https://twitter.com/YuFeng10
  email:             yuzz.feng@gmail.com

# Custom vars
version:             1.0.0
